---
title: "About"
format:
  html:
    toc: false
---

I am a PhD student in Carnegie Mellon's Statistics and Data Science department. In May 2024, I graduated *magna cum laude* from Pomona College with a double major in mathematics and philosophy. At Pomona, I primarily worked with [Jo Hardin](https://hardin47.netlify.app), conducting research in both statistical genomics and data science ethics pedagogy.

Outside of research, I really enjoy teaching statistics and data science. This Fall, I will be the TA for 36-707: Regression Analysis, the introduction to regression and data analysis for first-year PhD students in Statistics & Data Science at Carnegie Mellon. Previously, I have been a TA for the Carnegie Mellon Sports Analytics Summer Camp where I co-led some early lectures on data analysis in R with my cohort-mate, [Erin Franke](https://efranke22.github.io/), a Head TA for 36-226: Introduction to Statistical Inference, and a graduate TA for 36-600: Overview of Statistical Learning and Modeling. At Pomona, I served as a peer mentor for various mathematics and statistics courses, as well as a first-year writing course and an introductory genetics course.

Another primary interest of mine is philosophy, particularly (feminist) philosophy of science, ethics, and (social) epistemology. I hope to stay engaged in philosophy and, with that, work to better understand and grapple with the ethical dimensions of statistical technologies while completing my PhD.

## Ongoing Research Projects

**A shortlist of ongoing research projects (as of July 2025):**

- Predicting Avoidance Ties in Avoidance Networks Leveraging only the Positive Network between the Same Individuals and Basic Node-Level Characteristics (Advanced Data Analysis project, in collaboration with [Nynke Niezink](https://www.stat.cmu.edu/~nynke/) and Eva Jaspers).

- Selecting Chip-Seq Normalization Methods from the Perspective of their Technical Conditions (in collaboration with Jo Hardin and Danae Schulz) -- recently accepted to *Briefings in Bioinformatics*.

- Analyzing Statistics Students' Writing Before and After the Emergence of Large Language Models (in collaboration with Erin Franke) -- presented progress during the Research Satellite at *USCOTS 2025*.

- Teaching Data Cleaning and Wrangling with R's `data.table` Package (also in collaboration with Erin Franke) -- presented at the Poster and Beyond Session at *USCOTS 2025*.

## Education

{{< iconify zondicons:education size=xl >}} PhD in Statistics (in progress)

Carnegie Mellon University

{{< iconify zondicons:education size=xl >}} BA in Mathematics and Philosophy (May 2024)

Pomona College

## Contact

{{< iconify material-symbols:mail-sharp size=xl >}} [scolando\@andrew.cmu.edu](mailto:scolando@andrew.cmu.edu)
