---
title: "Curriculum Vitae"
subtitle: "Last updated August 2025"
format:
  html:
    toc: true
    toc-title: "CV Section"
css: cv.css
---

{{< iconify teenyicons:pdf-outline size=l >}} <a href="Current-CV-Aug2025.pdf" target = "_blank"> <strong>PDF Version of Sara Colando's CV</strong></a>

## Education

**PhD in Statistics** [*2024 -- 2029 (Expected)*]{.cvdate}<br>Carnegie Mellon University, Pittsburgh, PA

**BA in Mathematics and Philosophy** [*May 2024*]{.cvdate}<br>Pomona College, Claremont, CA

-   Graduated *magna cum laude* and with departmental honors (GPA: 3.99/4.00)

## Publications and Papers

- **Peer-reviewed Articles**

  1.  Colando, S., Schulz, D., Hardin, J. **Selecting ChIP-Seq Normalization Methods from the Perspective of their Technical Conditions**, *Briefings in Bioinformatics*, 2025. <https://doi.org/10.1093/bib/bbaf431>

  2.  Colando, S. & Hardin, J. **Philosophy within Data Science Ethics Courses**, *Journal of Statistics and Data Science Education*, 2024. <https://doi.org/10.1080/26939169.2024.2394542>
  
- **In Progress**

  1. Colando, S., Franke, E., Reinhart A., **Analyzing Statistics Students' Writing Before and After the Emergence of Large Language Models**. In progress.

## Research Experience

**Pomona College Department of Mathematics and Statistics**<br>[Research Assistant to Dr. Johanna Hardin](https://scolando.github.io/research/chip-seq/chip-seq.html) [*May 2022 -- Aug 2025*]{.cvdate}

-   Analyzed between-sample normalization techniques by their technical assumptions to improve differential binding analysis practices for ChIP-Seq and similarly structured types of high-throughput data
-   Created reproducible ChIP-Seq read count simulations using R, Bash, and high-performance computing to examine how violating normalization method assumptions impacts the false discovery rate and power of identifying genomic regions with true differential DNA occupancy.

[Data Science Ethics Independent Project](https://scolando.github.io/research/data-ethics/data-ethics.html) (Supervisor: Dr. Johanna Hardin) [*May -- Oct 2023*]{.cvdate}

-   Synthesized resources and pedagogies of existing Data Science Ethics undergraduate courses to connect key ethical concepts to data science practices
-   Created a website to effectively communicate data science ethics concepts and relevant background information to a broad community of decision-makers
-   Aided in Pomona College's development of an ethics course for the recently approved data science minor

**Carnegie Mellon University Department of Statistics and Data Science**<br>[Research Assistant to Dr. Ron Yurko](https://scolando.github.io/research/horses/horses.html) [*May -- Aug 2023*]{.cvdate}

-   Performing mixture-model clustering analysis to discover trends in movement patterns for injured racehorses
-   Identifying horses who under-raced through residual analysis of a created expected race count model
-   Engaged in 8 weeks of lectures about popular statistical analysis techniques, data engineering, and novel data science methodologies employed in sports analytics

**Self-Directed Project**<br>[Data Analysis and Visualization Creator](https://scolando.github.io/projects.html)[*Jan 2021 -- May 2024*]{.cvdate}

-   Conducting exploratory data analysis in R to improve data visualization and communication skills every week using data provided by the "R for Data Science" Online Learning Community
-   Helping students new to R become more familiar with the programming language and troubleshoot errors in 2-hour Pomona TidyTuesday workshop offered each week

**University of California, San Diego Halıcıoğlu Data Science Institute**<br> [Intelligence, Data, Ethics, and Society (IDEAS) Summer Institute Participant](https://sites.google.com/view/ideas-summer-program/) [*Aug 2023*]{.cvdate}

-   Participated in workshops taught by experts in domains like data science, AI, philosophy, and law to improve critical and interdisciplinary thinking on data science and AI ethics topics
-   Collaborated with three other students on a two-week research project, examining practical methods of implementing responsible data science and AI practices in a California wildfire resource allocation algorithm

**University of Michigan School of Public Health**<br>[Big Data Summer Institute Research Assistant to Dr. Nikola Banovic](https://scolando.github.io/esearch/tumor-mri/tumor-mri.html) [*June -- Aug 2022*]{.cvdate}

-   Collaborated with three other students to implement a partially Bayesian neural network to quantify and communicate prediction uncertainty in a supervised brain tumor segmentation model via Python's PyTorch and TensorFlow packages
-   Participated in 6 weeks of lectures about ethical data collection practice in healthcare, probability and statistical theory, and the ethical implications of using statistics and computer science methods in healthcare settings

## Teaching Experience

**Carnegie Mellon Department of Statistics and Data Science**<br> Graduate Teaching Assistant

-   36-707: Regression Analysis (Fall 2025)
-   Carnegie Mellon Sports Analytics Camp, *co-led four lectures* (Summer 2025)
-   36-226: Introduction to Statistical Inference, *Head TA* (Spring 2025)
-   36-600: Overview of Statistical Learning and Modeling (Fall 2024)

**Pomona College**<br> Course Mentor and Grader 

-   MATH158: Statistical Linear Models (Spring 2024)
-   MATH058B: Introduction to Biostatistics (Spring 2023)
-   MATH060: Linear Algebra (Fall 2021)
-   MATH030: Calculus I, Grader Only (Spring 2021)
-   ID001: First-year Interdisciplinary Seminar: I Disagree (Fall 2023)
-   BIOL040: Introductory Genetics with Lab (Fall 2022)

1-2-1 Summer Bridge Program Teacher's Assistant (Summer 2021)

-   Led 1.5-hour meetings, twice per week, for three small cohorts of incoming Pomona College students
-   Organized group bonding by preparing icebreakers and virtual games for 40+ students in the program
-   Mathematical concepts taught: logic, statistics, calculus I and II, combinatorics, and number theory


## Presentations

- **Colando, S.** & Franke, E., "Analyzing Statistics Students’ Writing Before and After the Emergence of
Large Language Models" (poster), United States Conference on Teaching Statistics, July 2025
- Franke, E. & **Colando, S.** "Teaching Data Cleaning and Wrangling with R’s data.table Package"
(poster), United States Conference on Teaching Statistics, July 2025
- **Colando, S.** "Predicting Avoidance Ties within Social Networks (ADA Progress Update)", Networkshop Research Group, Carnegie Mellon University, March 2025
- **Colando, S.** & Franke E. "Computational Efficiency of R’s data.table Package", StatBytes, Carnegie Mellon University, March 2025
-   **Colando, S.** & Hardin, J. "[Philosophy within Data Science Ethics Courses](https://causeweb.org/cause/webinar/jsdse/2024-10)", CAUSE Webinar Series, October 2024
-   **Colando, S.**, Pipping, J., Wilson K. "Clustering Race Horse Movement Profiles to Discover Trends in Injured Horses", Carnegie Mellon Sports Analytics Conference 2023, November 2023
-   **Colando, S.** "Analyzing Data Science Ethics Pedagogies", Claremont Center for Mathematical Sciences Poster Session, September 2023
-   **Colando, S.** "Analyzing Data Science Ethics Pedagogies", Intensive Summer Experience Symposium, September 2023
-   **Colando, S.**, Pipping, J., Wilson K. "Clustering Race Horse Movement Profiles to Discover Trends in Injured Horses", Summer Undergraduate Research Experience (SURE) 2023 Project Showcase, July 2023
-   **Colando, S.** Panelist for "Pomona Funded Summer Experiences Informational Session", Family Weekend, October 2022
-   **Colando, S.** "Analyzing ChIP-Seq Normalization Techniques through the Lens of their Biological Assumptions", Intensive Summer Experience Symposium, September 2022
-   **Colando, S.** "Analyzing ChIP-Seq Normalization Techniques through the Lens of their Biological Assumptions", Claremont Center for Mathematical Sciences Poster Session, September 2022
-   Chu, C., **Colando, S.**, Nandi, D., Serrano, X. "Quantifying Uncertainty in a Tumor Segmentation Model", A Symposium on Big Data, Human Health, and Statistics. July 2022

## Grants

1. **Colando, S.** Graduate Student Fellowship [*2025-2027*]{.cvdate}\
  Amount: \$6,000 per year \
  Funder: Institute of Complex Social Dynamics, Carnegie Mellon University

2. **Colando, S.** & Franke, E. Travel Grant  [*2025*]{.cvdate}\
  Amount: \$500 \
  Funder: StatBytes, Carnegie Mellon Department of Statistics and Data Science

3. **Colando, S.** & Franke, E. data.table Ambassador Travel Grant [*2025*]{.cvdate} \
  Amount: \$2,700 \
  Funder: National Science Foundation (Award Abstract: #2303612)

## Leadership and Service

**Carnegie Mellon Department of Statistics and Data Science**<br> <a href="https://www.stat.cmu.edu/teachstat/" target = "_blank">TeachStat Working Group</a>, Mentorship Committee, Mentor for Undergraduates [*Aug 2024 -- Present*]{.cvdate}

**Pomona College Department of Philosophy**<br> Search and Selection Committee Member [*Aug 2023 -- Mar 2024*]{.cvdate}

**Pomona-Pitzer Athletics**<br> Varsity Women's Cross Country Team Captain [*Aug -- Nov 2023*]{.cvdate}

## Honors and Awards

- Passed First-Year PhD Data Analysis Exam with Distinction, Statistics and Data Science Department, Carnegie Mellon University [*2025*]{.cvdate}
-   Blair Nixon Award, Pomona College [*2024*]{.cvdate}
-   Bruce Jay Levy Senior Prize, Department of Mathematics and Statistics, Pomona College [*2024*]{.cvdate}
-   W.T. Jones Prize in Philosophy, Department of Philosophy, Pomona College [*2024*]{.cvdate}
-   Phi Beta Kappa, Southern California Chapter [*2024*]{.cvdate}
-   Sigma Xi, Claremont Colleges Chapter [*2024*]{.cvdate}
-   Pomona College Scholar [*2020 -- 2024*]{.cvdate}
-   Cross Country and Track and Field Varsity Letter Recipient, Pomona-Pitzer Athletics [*2020 -- 2024*]{.cvdate}
